modLoader="kotori_scala"
loaderVersion="[2.13.6-build-3, ),[37,)"
issueTrackerURL = "https://github.com/Kotori316/FluidTank/issues"
license = "All Rights Reserved."
[[mods]]
modId = "fluidtank"
version = "${file.jarVersion}"
displayName = "FluidTank"
updateJSONURL = "https://raw.githubusercontent.com/Kotori316/FluidTank/1.17/update.json"
displayURL = "https://github.com/Kotori316/FluidTank"
credits = "Kotori316"
authors = "Kotori316"
description = '''
Add large fluid tanks.'''
[[dependencies.fluidtank]]
    modId = "forge"
    mandatory = true
    versionRange = "[37.0.86,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.fluidtank]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.17.1, )"
    ordering = "NONE"
    side = "BOTH"
