modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL = "https://github.com/Kotori316/FluidTank/issues"
license = "All Rights Reserved."
[[mods]]
modId = "fluidtank"
version = "${file.jarVersion}"
displayName = "FluidTank"
updateJSONURL = "https://raw.githubusercontent.com/Kotori316/FluidTank/1.17/update.json"
displayURL = "https://github.com/Kotori316/FluidTank"
credits = "Kotori316"
authors = "Kotori316"
description = '''
Add large fluid tanks.'''
[[dependencies.fluidtank]]
    modId = "forge"
    mandatory = true
    versionRange = "[37.0.84,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.fluidtank]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.17.1, )"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.fluidtank]]
    modId = "slp"
    mandatory = true
    versionRange = "[2.13.6, )"
    ordering = "NONE"
    side = "BOTH"
