name: Java CI 2

on:
  push:
    branches:
      - "1.16"

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 1.8, 11 ]
        # List of forge I want to check the source compiles successfully.
        forge: [ 1.16.3-34.1.0, 1.16.3-34.1.42]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      #- name: download_assets
      #  run: |
      #    chmod +x ./gradlew
      #    ./gradlew downloadAssets || ./gradlew downloadAssets || sleep 30s && ./gradlew downloadAssets
      #  continue-on-error: true
      - id: check-parameter
        run: chmod +x ./gradlew && ./gradlew checkMethod --no-daemon
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          CI_FORGE: ${{ matrix.forge }}
      - name: Test-JUnit
        run: chmod +x ./gradlew && ./gradlew --no-daemon test
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          CI_FORGE: ${{ matrix.forge }}
      - name: Upload failed test report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          path: build/reports/tests/*
          name: Test-Report-${{ matrix.java }}-${{ matrix.forge }}