name: Java CI

on:
  push:
    branches:
      - "1.16"

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 1.8, 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle16-${{ hashFiles('**/forge_version.properties') }}
      - id: check-parameter
        run: chmod +x ./gradlew && ./gradlew checkMethod --no-daemon
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - name: Download Assets for Cache
        run: |
          chmod +x ./gradlew && (./gradlew clean || true)
          ( ./gradlew downloadAssets extractNatives || ./gradlew downloadAssets extractNatives || \
          (sleep 30s && ./gradlew downloadAssets extractNatives) || true)
      - name: Test-JUnit
        run: chmod +x ./gradlew && ./gradlew --no-daemon test
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - name: Upload failed test report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          path: build/reports/tests/*
          name: Test-Report-${{ matrix.java }}

  build-publish:
    runs-on: ubuntu-latest
    needs: [ check ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle16
      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew assemble --no-daemon --continue
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: build/libs/*
          name: ${{ github.event.repository.name }}-${{ github.run_number }}

  cross-check-JUnit:
    runs-on: ubuntu-latest
    needs: [ check ]
    strategy:
      fail-fast: false
      matrix:
        java: [ 1.8, 11 ]
        forge: [ 1.16.4-35.1.37, latest ]
    steps:
      - uses: actions/checkout@v2
        if: ${{ matrix.forge == 'latest' }}
        with:
          repository: "Kotori316/SLP-example"
      - name: Get latest version
        if: ${{ matrix.forge == 'latest' }}
        run: |
          version=$(python3 get_latest_forge.py "1.16.5-latest")
          echo "FORGE_LATEST=1.16.5-$version" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle16
      - name: Test-JUnit
        run: |
          if [ $CI_FORGE = "latest" ]; then
            export CI_FORGE=$FORGE_LATEST
            echo $FORGE_LATEST
          fi
          chmod +x ./gradlew && ./gradlew --no-daemon test
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          CI_FORGE: ${{ matrix.forge }}
      - name: Upload failed test report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          path: build/reports/tests/*
          name: Test-Report-${{ matrix.java }}

  cross-check-runData:
    runs-on: ubuntu-latest
    needs: [ build-publish ]
    strategy:
      fail-fast: false
      matrix:
        java: [ 1.8, 11 ]
        forge: [ 1.16.4-35.1.37, latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "Kotori316/SLP-example"
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle16
      - name: Download Mod Jar
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ github.run_number }}
          path: work/
      - name: move files
        run: ls -al work && mkdir --parents run/mods && mv work/*-deobf.jar run/mods/ && ls -al run/mods
      - name: download_assets
        run: |
          if [ $CI_FORGE = "latest" ]; then
            version=$(python3 get_latest_forge.py "1.16.5-latest")
            export CI_FORGE="1.16.5-$version"
          fi
          chmod +x ./gradlew && (./gradlew clean downloadAssets || true)
          ( (./gradlew compileScala || ./gradlew clean) || (./gradlew compileScala || ./gradlew clean) || (sleep 10s && ./gradlew compileScala) )
        continue-on-error: true
        env:
          CI_FORGE: ${{ matrix.forge }}
      - name: Test with JUnit and runData
        run: |
          if [ $CI_FORGE = "latest" ]; then
            version=$(python3 get_latest_forge.py "1.16.5-latest")
            export CI_FORGE="1.16.5-$version"
          fi
          chmod +x ./gradlew && ( ./gradlew --no-daemon runData || ./gradlew --no-daemon runData)
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_FORGE: ${{ matrix.forge }}
          CI_MODS: "fluidtank"