name: Java CI

on:
  push:
    branches:
      - "1.16"

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 1.8, 11 ]
        # java: [ 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle16-${{ hashFiles('**/forge_version.properties') }}
      #- name: download_assets
      #  run: |
      #    chmod +x ./gradlew
      #    ./gradlew downloadAssets || ./gradlew downloadAssets || sleep 30s && ./gradlew downloadAssets
      #  continue-on-error: true
      - id: check-parameter
        run: chmod +x ./gradlew && ./gradlew checkMethod --no-daemon
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - name: Test-JUnit
        run: chmod +x ./gradlew && ./gradlew --no-daemon test
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      #- name: Test-RunData
      #  run: chmod +x ./gradlew && ./gradlew --no-daemon runData
      #  continue-on-error: true
      #  env:
      #    REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      #- id: check-test-started
      #  run: |
      #    [ -f test_started.txt ]
      #- id: check-error
      #  run: |
      #    ! [ -f error-trace.txt ]
      #- id: show-failure-log
      #  if: failure()
      #  run: cat error-trace.txt

  build-publish:
    runs-on: ubuntu-latest
    needs: [ check ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle16-${{ hashFiles('**/forge_version.properties') }}
      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew build --no-daemon --continue
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: build/libs/*
