name: Java CI

on:
  push:
    branches:
      - "1.16.2-fabric"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 1.8, 11 ]
        # java: [ 11 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/forge_version.properties') }}
      - name: Check Paramater
        run: chmod +x ./gradlew && ./gradlew gCO
      - name: Precompile
        run: chmod +x ./gradlew && ./gradlew compileScala
      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew build
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
