name: Java CI

on:
  push:
    branches:
      - "1.17-fabric"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 16 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      #- uses: actions/cache@v2
      #  with:
      #    path: ~/.gradle/caches
      #    key: ${{ runner.os }}-gradle-${{ hashFiles('**/forge_version.properties') }}
      - name: Check Paramater
        run: chmod +x ./gradlew && ./gradlew gCO
      - name: Check Dependencies
        run: chmod +x ./gradlew && ./gradlew dependencies
      - name: Precompile
        run: chmod +x ./gradlew && ./gradlew compileScala
      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew build
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
